Add stars for BeatLeader and add Ranked for beatleader
RedBrumbler/SongDetails pull request #5
Opened 2023-04-30 21:13 UTC by FrozenAlex

Pullrequest to track changes

2023-04-30 21:54 UTC, FrozenAlex commented
The actual change is not live yet, we are using the new test file I reuploaded here (Add it as a source in  DataGetter to test)
```cpp
{ "Test", "https://raw.githubusercontent.com/FrozenAlex/TestSongDetails/master/SongDetailsCache.proto.gz" }
```

2023-05-01 12:26 UTC, RedBrumbler commented
Could you pull in the upstream changes so the workflow will run? thx

2023-05-09 09:08 UTC, RedBrumbler requested changes

2023-05-09 09:08 UTC, RedBrumbler commented on shared/Data/Song.hpp
> +            /// @brief Gets the maximum star value in all diffs of this song for BeatLeader
please fix these comments to be actually minimum and maximum

2023-05-09 09:08 UTC, RedBrumbler commented on src/Data/Song.cpp
> +        return min([](const auto& diff){ return diff.rankedSS() ? diff.starsBL : std::numeric_limits<float>::max(); });
this check is wrong as it uses rankedSS to check for BL rankedness

2023-05-09 09:08 UTC, RedBrumbler commented on src/Data/Song.cpp
> +        return min([](const auto& diff){ return diff.rankedSS() ? diff.starsBL : std::numeric_limits<float>::max(); });
also please use the `hasFlags` method for the if checks, instead of `rankedStates != RankedStates::BeatleaderRanked`

2023-05-09 09:08 UTC, RedBrumbler commented on src/Data/SongDifficulty.cpp
> +        return this->rankedBL() || this->rankedSS();
minor, but please put rankedSS() in front, I think that'd be better for this as SS is more likely to have a song ranked atm

2023-05-09 09:08 UTC, RedBrumbler commented on src/Data/SongDifficulty.cpp
> +    [[deprecated("This function is deprecated. It only works for scoresaber ranked difficulties and is not accurate.")]]
is it really deprecated though? it's made to not be accurate, and pp is strictly scoresaber, not BL anyways

2023-05-09 10:12 UTC, RedBrumbler commented
lgtm

2023-05-09 10:13 UTC, RedBrumbler approved these changes

2023-05-09 10:14 UTC, merged